apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"Hello, world!\"; sleep 10; done"]
  restartPolicy: OnFailure
